version: '3'

services:
  zookeeper:
    image: shivashankervuppula/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper
    
  kafka:
    image: shivashankervuppula/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTIZED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC:
        - "create_orders:1:3"
        - "cancel_orders:1:3"